<?php

namespace lahaut\BaloonWatcherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GPSRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GPSRecordRepository extends EntityRepository
{
}
