parameters:
#    baloon_watcher.example.class: lahaut\BaloonWatcherBundle\Example

services:
#    baloon_watcher.example:
#        class: %baloon_watcher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
